### ISSUE TITLE
Publish termsheets.me user guide

### ISSUE THREAD

**Issue by Ro5s** [open-esq/termsheet#1]
@afagella 

I'd like to bounty [3 OECC](https://etherscan.io/token/0xbf02e44b1c2ca5d2aef767e70d93fc2b8977bd5a) for doing a very brief writeup on [termsheets.me](termsheets.me)

*Basically,*

(1) What forms are these based on?

***Y-Combinator***

- **Series AA Term Sheet:** https://www.docracy.com/5/y-combinator-series-aa-termsheet# 

> Note: These documents are from http://ycombinator.com/seriesaa.html and include the following disclaimer (from that site): Y Combinator and Wilson Sonsini Goodrich & Rosati are happy to announce the Series AA Equity Financing Documents. Their goal is to make angel funding rounds for startups easier for both sides. These documents were originally created for YC-funded startups to use when raising angel rounds. They seem to have worked well in tria l runs so far, so we're open-sourcing them. While they may not be suitable for all situations, the goal was to make the terms fairly neutral. So while we would of course advise both parties using these documents to have their lawyers look at them, they provide a starting point that we hope can be used in many situations without too many modifications. Needless to say, neither YC nor WSGR assumes any responsibility for any consequence of using these documents.

- **Series A Term Sheet:** https://www.ycombinator.com/series_a_term_sheet/ 

>  While working with companies in YC’s Series A program we’ve noticed a common problem: founders don’t know what “good” looks like in a term sheet. This makes sense, because it is often, literally, the first time in their careers that they’ve seen one. This puts founders at a significant disadvantage because VCs see term sheets all the time and know what to expect. Because we’ve invested in so many founders over the years and have seen hundreds of Series A term sheets, we know what “good” looks like. We work with our founders to understand where terms diverge from “good”, what they can do about that divergence, and when and how it makes sense to negotiate [ . . . . ]

- **SAFE:** https://www.ycombinator.com/documents/  - "Safe: Valuation Cap, no Discount"

> Y Combinator introduced the safe (simple agreement for future equity) in late 2013, and since then, it has been used by almost all YC startups and countless non-YC startups as the main instrument for early-stage fundraising. [ . . . . ]

> Guide: https://www.ycombinator.com/docs/Post%20Money%20Safe%20User%20Guide.pdf

**Comment by afagella** [comment]
### **FAQ** ###

**1. Where did these forms originate?**
- The [Series A Term Sheet](https://www.ycombinator.com/documents/), Series AA Term Sheet, and [SAFE ](https://www.ycombinator.com/series_a_term_sheet/) were developed by [Y Combinator](https://www.ycombinator.com/) and [Wilson Sonsini Goodrich & Rosati](https://www.wsgr.com) with the goal of making early fundraising rounds easier for founders and investors. 

**2. Why should I trust these forms?**
- The creators of these forms are among the most experienced and respected organizations for accelerating and representing startups. They believe these forms feature "standard and clean terms from a good Silicon Valley VC . . . [f]ounders with a lot of negotiating leverage can sometimes do better, and the converse is true too." Y Combinator provides details about negotiating specific terms for the [Series A](https://www.ycombinator.com/series_a_term_sheet/) and [SAFE](https://www.ycombinator.com/documents/).
- **_Anyone using these forms should first review them with their attorney. OpenESQ, OpenLaw, and any affiliated parties are not responsible for any consequences that arise from using these documents._**

**3. Why should someone should use forms through OpenESQ?**
- Explain why OpenESQ/OpenLaw are a better/more dynamic way to represent agreements. Blockchain signature etc. 

**4. What else should I know?**

**Comment by Ro5s** [comment]
This is a great start! Mea culpa for lag on here. Going to add these to sep file as start! Many thanks

**Comment by afagella** [comment]
> ### **FAQ**

> **1. What is OpenESQ?**
> **Ross, I think you should handle this one :)**
>
> **2. Where did these forms originate?**
> 
> * The [Series A Term Sheet](https://www.ycombinator.com/documents/), Series AA Term Sheet, and [SAFE ](https://www.ycombinator.com/series_a_term_sheet/) were developed by [Y Combinator](https://www.ycombinator.com/) and [Wilson Sonsini Goodrich & Rosati](https://www.wsgr.com) with the goal of making early fundraising rounds easier for founders and investors.
> 
> **3. Why should I trust these forms?**
> 
> * The creators of these forms are among the most experienced and respected organizations for accelerating and representing startups. Y Combinator believes these forms feature "standard and clean terms from a good Silicon Valley VC . . . [f]ounders with a lot of negotiating leverage can sometimes do better, and the converse is true too." Y Combinator provides information for negotiating specific terms for the [Series A](https://www.ycombinator.com/series_a_term_sheet/) and [SAFE](https://www.ycombinator.com/documents/).
> * **_Anyone using these forms should first review them with an attorney. OpenESQ, OpenLaw, and any affiliated parties are not responsible for any consequences that arise from using these documents._**
> 
> **4. How has OpenESQ improved these forms?**
>  OpenESQ forms are built on [OpenLaw](https://www.openlaw.io/faq?ref=footer), "a blockchain-based protocol for the creation and execution of legal agreements. Using OpenLaw, lawyers can more efficiently engage in transactional work and digitally sign and store legal agreements in a highly secure manner, all while leveraging next generation blockchain-based smart contracts." 
> Using OpenLaw's markup language technology, OpenESQ's attorneys have taken industry-standard legal documents into the 21st century. OpenESQ's documents are more than just digital paper - they can perform tasks like making payments, "speaking" to other agreements through computer code, and storing a party's signature generated by the Ethereum blockchain. Automating tasks reduces transaction costs (like payments to intermediaries), limits opportunities for human error, and gives precious time back to our clients. The distributed ledger technology of the Ethereum blockchain also ensures all documents remain secure, organized, and compatible with future upgrades like [Ethereum 2.0](https://github.com/ethereum/eth2.0-specs/blob/dev/README.md).

> **5. What else should I know?**
**Ross, where should we go from here?**
